### ISSUE TITLE
lt's about the paper

### ISSUE THREAD

**Issue by qi0523** [mason-leap-lab/FaaSNet#2]
Why would you like to deploy dynamic vm pool？I guess when the load is light，vms are possibly recycled to save energy?

**Comment by tddg** [comment]
When the load is light and already-provisioned VMs are sitting idled, these cold VMs would be reclaimed to save resources for the service provider. A provisioned VM occupies resources and if those resources are not being utilized, it hurts the TCO.

**Comment by willyqi** [comment]
Thanks for your reply.

**Comment by qi0523** [comment]
Thanks for your reply. By the way, what is the capacity of the vm disk? If the capacity of the disk is small, is it frequent that images are deleted and downloaded?

**Comment by wangaoone** [comment]
> Thanks for your reply. By the way, what is the capacity of the vm disk? If the capacity of the disk is small, is it frequent that images are deleted and downloaded?

Yes. The disk of each VMs is small. The disk size always sits around tens of GB. And also the images would be frequently downloaded.

**Comment by qi0523** [comment]
Thanks

**Comment by qi0523** [comment]
l have two questions about the function cold start traces.
One problem is that latency in seconds is not reasonable(Some functions have the latency of more than 1000s).The other is whether each function cold starts at least once every day? In regions 2, the number of function cold start exceeds 1.1 million. So, there are more functions should be invoked every day? How many functions are invoked in region 2 every day? Thanks for your reply!
